a=10;
b=3;
sum=a+b;
sub=a-b;
div=a/b;
mult=a*b;
fprintf('a: %d\n', a);
fprintf('b: %d\n', b);
fprintf('a + b: %d\n', sum);
fprintf('a - b: %d\n', sub);
fprintf('a / b: %.3f\n', div);  
fprintf('a * b: %d\n', mult);
