number1 = 10;
number2 = 3;
sum = number1 + number2;
diffLowerFromGreater = number1 - number2;
diffGreaterFromLower = number2 - number1;
product = number1 * number2;
divLargeBySmall = number1 / number2;
divSmallByLarge = number2 / number1;

fprintf("Sum of 10 and 3: " + sum + "\n" ...
     + "Difference is 3 from 10: " + diffLowerFromGreater + "\n" ...
      + "Difference is 10 from 3: " + diffGreaterFromLower + "\n"...
      + "Multiplication of 10 and 3: " + product + "\n" ...
      + "Division 10 divided by 3: " + divLargeBySmall + "\n" ...
       + "Division 3 divided by 10: " + divSmallByLarge);